pipeline:
    build:
        image: haavardlian/cmake:latest
        pull: true
        commands:
            - mkdir build
            - cd build
            - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} 
            - make

matrix:
    BUILD_TYPE:
        - Debug
        - Release
