pipeline:
    build:
        image: debian:latest
        commands:
            - apt update
            - apt install -y cmake make g++ gcc
            - mkdir build
            - cd build
            - cmake ..
            - make
