language: cpp

compiler:
  - clang

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

install:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - make
  - cd ..
  
script:
  - cd build
  - cpack
